#!/usr/bin/env bash

# ncp-flat-kubeconfig(1) is a utility to merge kubeconfig for nks 

# Copyright 2022 SysNet4Admin (Hoon Jo)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[ -n $DEBUG ]] && set -x
set -eou pipefail
#IFS=$'\n\t'

KUBECONFIG='kubeconfig.yaml'

backup_kubeconfig(){
cp ~/.kube/config ~/.kube/config.ori 
}

rename_kubeconfig(){
pUUID=`cat $KUBECONFIG | yq -r '.clusters[].cluster.server' | cut -c 9-12`
REGION=`cat $KUBECONFIG | yq -r '.users[].user[].args[4]'`
# Change context name from original to each cluster
sed -i'' -e "s|nks-user@kubernetes|nks-$pUUID|g" $KUBECONFIG

# Change user name from original to each cluster 
sed -i'' -e "s|kubernetes|nks-$REGION-$pUUID|g"  $KUBECONFIG
}

merge_kubeconfig(){
KUBECONFIG=~/.kube/config:$KUBECONFIG kubectl config view --flatten > /tmp/config
}

replace_kubeconfig(){
mv /tmp/config ~/.kube/config
}


main() {
  # backup original kubeconfig. 
  # when you have issues, recover by ~/.kube/config.ori manually 
  backup_kubeconfig

  # due to dup cluster name 
  rename_kubeconfig 

  # actual step to flat the kubeconfig 
  merge_kubeconfig
  replace_kubeconfig && echo "successfully flatting NKS's kubeconfig"

}

main "$@"

